Fix for VS2012 build.
Problem
error C2780: 'std::shared_ptr<_Ty> std::make_shared(_V0_t &&,_V1_t &&,_V2_t &&,_V3_t &&,_V4_t &&)' : expects 5 arguments - 6 provided

Solution
Increase the limit for VS2012's simulated variadic templates from 5 to 6 parameters in the core_serialization library.

NGT-1410