Attempt to fix Mac compilation.
Problem
python27_interface_test.cpp:46:18: error: object of type 'PropertyAccessor' cannot be assigned because its copy assignment operator is implicitly deleted

Solution
Implement missing copy assignment for PropertyAccessor

NGT-1561